server:
  port: 8080
  http2:
    enabled: true
spring:
  application:
    name: Marvel API    
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:marvel
    username: marvel
    password:
  jpa:
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework: ERROR
