spring:
  profiles: dev
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:saogabriel
    username: saogabriel
    password:
  jpa:
    show-sql: true